jobs:
  close-issues:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: need reproduction
      uses: actions-cool/issues-helper@v3
      with:
        actions: close-issues
        inactive-day: 3
        labels: need reproduction
        token: ${{ secrets.GITHUB_TOKEN }}
name: Issue Close Require
on:
  repository_dispatch:
    types: trigger-ga___issue-close-require.yml
