jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dessant/lock-threads@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        issue-inactive-days: '14'
        issue-lock-reason: ''
        process-only: issues
name: Lock Closed Issues
on:
  repository_dispatch:
    types: trigger-ga___lock-closed-issues.yml
permissions:
  issues: write
