jobs:
  main:
    name: Semantic Pull Request
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
name: Semantic Pull Request
on:
  repository_dispatch:
    types: trigger-ga___semantic-pull-request.yml
